- type: professional-pc
  key: 2021-08-11
  chair: false
  description: 30th USENIX Security Symposium (Sec'21) 
- type: professional-pc
  key: 2021-02-01
  chair: true
  description: 6th Workshop on Advances in Secure Electronic Voting (Voting'21)
- type: professional-pc
  key: 2020-10-01
  chair: false
  description: Fifth International Joint Conference on Electronic Voting (E-Vote-ID'20)
- type: professional-external
  key: 2020-03-20
  description: Election Law Journal
- type: professional-pc
  key: 2020-02-01
  chair: true
  description: 5th Workshop on Advances in Secure Electronic Voting (Voting'20)
- type: professional-external
  key: 2019-11-01
  description: ACM Conferences on Human Factors in Computing Systems (CHI'20) 
- type: professional-external
  key: 2019-08-01
  description: USENIX Security Symposium (Sec'19) 
- type: professional-external
  key: 2018-11-01
  description: ACM Internet Measurement Conference (IMC'18) 
- type: professional-external
  key: 2018-10-01
  description: ACM Conference on Computer and Communications Security (CCS'18) 
- type: professional-external
  key: 2018-08-01
  description:  International Symposium on Research in Attacks, Intrusions, and Defenses (RAID'18) 
- type: professional-external
  key: 2017-10-01
  description: ACM Conference on Computer and Communications Security (CCS'17) 
- type: professional-external
  key: 2017-02-01
  description: Network and Distributed System Security Symposium (NDSS'17) 
- type: professional-external
  key: 2016-08-01
  description: IEEE Conference on Privacy, Security, and Trust (PST'16) 
